default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default

test:
  <<: *default

production:
  primary: &primary_production
    <<: *default
  cache:
    <<: *primary_production
    database: ticket_manager_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ticket_manager_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ticket_manager_production_cable
    migrations_paths: db/cable_migrate
